scheduler:
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 256Mi

worker:
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 512Mi

jupyter:
  enabled: false
